repository: mhiro2/envdesk

coverage:
  exclude:
    - "xxx"

codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
  test:
    - "**/*_test.go"

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report

comment:
  if: is_pull_request
  hideFooterLink: false

summary:
  if: is_pull_request
  hideFooterLink: false

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}/octocov-report
